/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedResumesIndexRouteImport } from './routes/_authenticated/resumes/index'
import { Route as AuthenticatedResumesIdRouteImport } from './routes/_authenticated/resumes/$id'
import { Route as AuthenticatedResumeEnhancerResumeIdRouteImport } from './routes/_authenticated/resume-enhancer/$resumeId'
import { Route as AuthenticatedResumesIdEnhanceRouteImport } from './routes/_authenticated/resumes/$id/enhance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumesIndexRoute =
  AuthenticatedResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumesIdRoute = AuthenticatedResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeEnhancerResumeIdRoute =
  AuthenticatedResumeEnhancerResumeIdRouteImport.update({
    id: '/resume-enhancer/$resumeId',
    path: '/resume-enhancer/$resumeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumesIdEnhanceRoute =
  AuthenticatedResumesIdEnhanceRouteImport.update({
    id: '/enhance',
    path: '/enhance',
    getParentRoute: () => AuthenticatedResumesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/resume-enhancer/$resumeId': typeof AuthenticatedResumeEnhancerResumeIdRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRouteWithChildren
  '/resumes/': typeof AuthenticatedResumesIndexRoute
  '/resumes/$id/enhance': typeof AuthenticatedResumesIdEnhanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/resume-enhancer/$resumeId': typeof AuthenticatedResumeEnhancerResumeIdRoute
  '/resumes/$id': typeof AuthenticatedResumesIdRouteWithChildren
  '/resumes': typeof AuthenticatedResumesIndexRoute
  '/resumes/$id/enhance': typeof AuthenticatedResumesIdEnhanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/resume-enhancer/$resumeId': typeof AuthenticatedResumeEnhancerResumeIdRoute
  '/_authenticated/resumes/$id': typeof AuthenticatedResumesIdRouteWithChildren
  '/_authenticated/resumes/': typeof AuthenticatedResumesIndexRoute
  '/_authenticated/resumes/$id/enhance': typeof AuthenticatedResumesIdEnhanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/resume-enhancer/$resumeId'
    | '/resumes/$id'
    | '/resumes/'
    | '/resumes/$id/enhance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/resume-enhancer/$resumeId'
    | '/resumes/$id'
    | '/resumes'
    | '/resumes/$id/enhance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/resume-enhancer/$resumeId'
    | '/_authenticated/resumes/$id'
    | '/_authenticated/resumes/'
    | '/_authenticated/resumes/$id/enhance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/': {
      id: '/_authenticated/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AuthenticatedResumesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/$id': {
      id: '/_authenticated/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/resumes/$id'
      preLoaderRoute: typeof AuthenticatedResumesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-enhancer/$resumeId': {
      id: '/_authenticated/resume-enhancer/$resumeId'
      path: '/resume-enhancer/$resumeId'
      fullPath: '/resume-enhancer/$resumeId'
      preLoaderRoute: typeof AuthenticatedResumeEnhancerResumeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/$id/enhance': {
      id: '/_authenticated/resumes/$id/enhance'
      path: '/enhance'
      fullPath: '/resumes/$id/enhance'
      preLoaderRoute: typeof AuthenticatedResumesIdEnhanceRouteImport
      parentRoute: typeof AuthenticatedResumesIdRoute
    }
  }
}

interface AuthenticatedResumesIdRouteChildren {
  AuthenticatedResumesIdEnhanceRoute: typeof AuthenticatedResumesIdEnhanceRoute
}

const AuthenticatedResumesIdRouteChildren: AuthenticatedResumesIdRouteChildren =
  {
    AuthenticatedResumesIdEnhanceRoute: AuthenticatedResumesIdEnhanceRoute,
  }

const AuthenticatedResumesIdRouteWithChildren =
  AuthenticatedResumesIdRoute._addFileChildren(
    AuthenticatedResumesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedResumeEnhancerResumeIdRoute: typeof AuthenticatedResumeEnhancerResumeIdRoute
  AuthenticatedResumesIdRoute: typeof AuthenticatedResumesIdRouteWithChildren
  AuthenticatedResumesIndexRoute: typeof AuthenticatedResumesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedResumeEnhancerResumeIdRoute:
    AuthenticatedResumeEnhancerResumeIdRoute,
  AuthenticatedResumesIdRoute: AuthenticatedResumesIdRouteWithChildren,
  AuthenticatedResumesIndexRoute: AuthenticatedResumesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
